- name: Install Apache and PHP using inventory-defined variables
  hosts: all
  become: true

  tasks:
    - name: Install Apache and PHP packages
      ansible.builtin.apt:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache and PHP packages on Fedora
      ansible.builtin.raw: dnf install -y {{ apache_package }} {{ php_package }}
      when: ansible_facts['distribution'] == "Fedora"
