- hosts: all
  become: true

  tasks:
    - name: Update repo index
      ansible.builtin.apt:
        update_cache: true

    - name: remove Apache2 package
      ansible.builtin.apt:
        name: apache2
        state: absent

    - name: remove support for php
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: absent

